# helm install \
#   cert-manager oci://quay.io/jetstack/charts/cert-manager \
#   --version v1.18.2 \
#   --namespace cert-manager \
#   --create-namespace \
#   --set crds.enabled=true \
#   -f values.yaml
config:
  featureGates:
    # Disable the use of Exact PathType in Ingress resources, to work around a bug in ingress-nginx
    # https://github.com/kubernetes/ingress-nginx/issues/11176
    ACMEHTTP01IngressPathTypeExact: false