apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-alias-poller # Renamed for clarity
  namespace: mlflow-webhook
  labels:
    app: mlflow-alias-poller
spec:
  replicas: 1 # Important: Run only one replica to avoid duplicate events due to state being in-memory
  selector:
    matchLabels:
      app: mlflow-alias-poller
  template:
    metadata:
      labels:
        app: mlflow-alias-poller
    spec:
      containers:
      - name: poller
        image: ghcr.io/endesapt/clash-royale-predictor-webhook:main
        ports:
        - name: http
          containerPort: 8080
        envFrom:
          - configMapRef:
              name: mlflow-poller-config
        imagePullPolicy: Always
        env:
          - name: PYTHONUNBUFFERED
            value: "0"
          - name: GITHUB_TOKEN
            valueFrom:
              secretKeyRef:
                name: github-pat-secret
                key: GITHUB_TOKEN
---
apiVersion: v1
kind: Service
metadata:
  name: mlflow-poller-service # Renamed for clarity
  namespace: mlflow-webhook
spec:
  selector:
    app: mlflow-alias-poller
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080