apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-alias-poller # Renamed for clarity
  namespace: mlflow-webhook
  labels:
    app: mlflow-alias-poller
spec:
  replicas: 1 # Important: Run only one replica to avoid duplicate events due to state being in-memory
  selector:
    matchLabels:
      app: mlflow-alias-poller
  template:
    metadata:
      labels:
        app: mlflow-alias-poller
    spec:
      containers:
      - name: poller
        image: ghcr.io/endesapt/clash-royale-predictor-poller:main
        ports:
        - name: http
          containerPort: 8080
        envFrom:
          - configMapRef:
              name: mlflow-poller-config
        env:
          - name: GITHUB_TOKEN
            valueFrom:
              secretKeyRef:
                name: github-pat-secret
                key: GITHUB_TOKEN
        # --- NEW: Health Checks for the Polling Service ---
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30 # Give the poller time to start
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 15
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: mlflow-poller-service # Renamed for clarity
  namespace: mlflow-webhook
spec:
  selector:
    app: mlflow-alias-poller
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080