name: Build and Push Docker Image to GHCR

on:
  push:
    branches:
      - main  # Or any branch you want to trigger the action on
  
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Necessary to push to GHCR
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }} # Uses the name of the user or bot that triggered the workflow
          password: ${{ secrets.GITHUB_TOKEN }} # The automatically created token
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}-trainer # ghcr.io/owner/repo-name
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./predictor  # Replace with the path to your Dockerfile directory
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha,scope=${{ github.workflow }}
          cache-to: type=gha,mode=max,scope=${{ github.workflow }}